"""
Django settings for integration_service project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from .logging_handler import CustomHTTPHandler
import json
import environ
import logging

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(env_file=Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'integration_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'integration_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        "LOCATION": "redis://redis:6379/1",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# 1 hour cache timeout
SPOONACULAR_CACHE_TIMEOUT = 3600


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

class LogFormatter(logging.Formatter):
    def format(self, record):
        try:
            record.service_name = 'Integration Service'
            return json.dumps({
            'service_name': record.service_name,
            'log_level': record.levelname,
            'message': record.getMessage()
        })
        except Exception as e:
            record.message = f"Error formatting log record: {e}"
            return super().format(record)
        
class ConsoleLogFormatter(logging.Formatter):
    def format(self, record):
        try:
            record.service_name = 'Integration Service'
            return super().format(record)
        except Exception as e:
            record.message = f"Error formatting log record: {e}"
            return super().format(record)
        
# Logging Settings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'custom': {
            '()': LogFormatter,
            'format': '%(service_name)s - %(levelname)s - %(message)s',
        },
        'console': {
            '()': ConsoleLogFormatter,
            'format': '%(service_name)s - %(levelname)s - %(message)s',
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
        'http': {
            'level': 'WARNING',
            'class': 'integration_service.logging_handler.CustomHTTPHandler',
            'host': env.str('LOGGING_HOST'),
            'url': env.str('LOGGING_ENDPOINT'),
            'method': 'POST',
            'formatter': 'custom',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'http'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Disable for production
CORS_ALLOW_ALL_ORIGINS: True

# URLS
AUTH_SERVICE_URL = env.str('AUTH_SERVICE_URL')
USER_SERVICE_URL = env.str('USER_SERVICE_URL')
SEARCH_SERVICE_URL = env.str('SEARCH_SERVICE_URL')
INTEGRATION_SERVICE_URL = env.str('INTEGRATION_SERVICE_URL')
LOGGING_SERVICE_URL = env.str('LOGGING_SERVICE_URL')

SPOONACULAR_API_KEY = env.str('API_KEY')
SPOONACULAR_BASE_URL = env.str('SPOONACULAR_BASE_URL')