services:
  api_gateway:
    build: ./api_gateway
    container_name: api-gateway
    env_file:
      - ./api_gateway/.env
    ports:
      - "8000:8000"
    networks:
      - backend_network

  auth_service:
    build: ./auth_service
    container_name: auth-service
    env_file:
      - ./auth_service/.env
    ports:
      - "8001:8000"
    depends_on:
      - api_gateway
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    networks:
      - backend_network

  user_service:
    build: ./user_service
    container_name: user-service
    env_file:
      - ./user_service/.env
    ports:
      - "8002:8000"
    depends_on:
      - api_gateway
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    networks:
      - backend_network

  search_service:
    build: ./search_service
    container_name: search-service
    env_file:
      - ./search_service/.env
    ports:
      - "8003:8000"
    depends_on:
      - api_gateway
    networks:
      - backend_network

  integration_service:
    build: ./integration_service
    container_name: integration-service
    env_file:
      - ./integration_service/.env
    ports:
      - "8004:8000"
    depends_on:
      - api_gateway
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend_network

  logging_service:
    build: ./logging_service
    container_name: logging-service
    env_file:
      - ./logging_service/.env
    ports:
      - "8005:8000"
    depends_on:
      - api_gateway
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    networks:
      - backend_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/16"
